version: "3"

services:
  postgres_dev:
    container_name: started_db
    image: postgres:14-alpine
    restart: always
    ports:
      - 3838:5432
    volumes:
      - /var/lib/started_db:/data/
    environment:
      - POSTGRES_PASSWORD=dev_password
      - POSTGRES_USER=dev_user
      - POSTGRES_DB=started_db